INSERT into Institution (institution_name, synergy_id) VALUES ("Abdijschool van Zevenkerken", 11034249);
INSERT into Institution (institution_name, synergy_id) VALUES ("Administration Communale de Châtelet", 99006639);
INSERT into Institution (institution_name, synergy_id) VALUES ("Administration communale de Dison", 99006361);
INSERT into Institution (institution_name, synergy_id) VALUES ("AG Digipolis Antwerpen", 99006278);
INSERT into Institution (synergy_id, institution_name) VALUES (11128728, "AG Stedelijk Onderwijs Antwerpen");
INSERT into Institution (synergy_id, institution_name) VALUES (11990031, "A-Maze");
INSERT into Institution (synergy_id, institution_name) VALUES (11035675, "Annuntiata-Instituut");
INSERT into Institution (synergy_id, institution_name) VALUES (99006448, "Anton De Doncker")
INSERT into Institution (synergy_id, institution_name) VALUES (99005851, "Arcadia vzw");
INSERT into Institution (synergy_id, institution_name) VALUES (11030403, "ASO Spijker");
INSERT into Institution (synergy_id, institution_name) VALUES (12000139, "Athenée Royal de Jambes");
INSERT into Institution (synergy_id, institution_name) VALUES (12990197, "ATHENEE ROYAL VICTOR HORTA");
INSERT into Institution (synergy_id, institution_name) VALUES (12990195, "Athenée Royal Crommelynck");
INSERT into Institution (synergy_id, institution_name) VALUES (95111819027,	"Athenee Royal De Gembloux");
INSERT into Institution (synergy_id, institution_name) VALUES (12990161, "Athenee Royal de Quievrain");
INSERT into Institution (synergy_id, institution_name) VALUES (12990094, "Athenee Royal Marche-Barvaux-Bomal");
INSERT into Institution (synergy_id, institution_name) VALUES (12990190, "Athenee royal Neufchâteau-Bertrix");
INSERT into Institution (synergy_id, institution_name) VALUES (12990043, "Athenee Royal Vielsalm-Manhay");
INSERT into Institution (synergy_id, institution_name) VALUES (11103101, "Atlas College vzw");
INSERT into Institution (synergy_id, institution_name) VALUES (99027698, "BA De Beemden");
INSERT into Institution (synergy_id, institution_name) VALUES (11123951, "Barnum");
INSERT into Institution (synergy_id, institution_name) VALUES (11122796, "Berthoutinstituut-Klein Seminarie 1");
INSERT into Institution (synergy_id, institution_name) VALUES (11035667, "Bisschoppelijk College");
INSERT into Institution (synergy_id, institution_name) VALUES (11033928, "Bovenbouw Sint-Gertrudis");
INSERT into Institution (synergy_id, institution_name) VALUES (11127738, "Broederschool");
INSERT into Institution (synergy_id, institution_name) VALUES (11026311, "BuBaO Spermalie");
INSERT into Institution (synergy_id, institution_name) VALUES (11973149, "Buitengewoon Secundair Onderwijs St.-Elisabeth");
INSERT into Institution (synergy_id, institution_name) VALUES (11035345, "Burgerschool");
INSERT into Institution (synergy_id, institution_name) VALUES (11129957, "BuSO Spermalie Secundaire school");
INSERT into Institution (synergy_id, institution_name) VALUES (11118372, "Campus Sint-Jan Berchmans");
INSERT into Institution (synergy_id, institution_name) VALUES (99000386, "CDO Newton");
INSERT into Institution (synergy_id, institution_name) VALUES (12000049, "CEFOR - IEPS");
INSERT into Institution (synergy_id, institution_name) VALUES (11126557, "Centrum voor Basiseducatie Halle-Vilvoorde");
INSERT into Institution (synergy_id, institution_name) VALUES (11035626, "College");
INSERT into Institution (synergy_id, institution_name) VALUES (11126871, "College Hagelstein 1");
INSERT into Institution (synergy_id, institution_name) VALUES (11034521, "College Ieper");
INSERT into Institution (synergy_id, institution_name) VALUES (1412819, "Collège  Notre Dame de la Paix");
INSERT into Institution (synergy_id, institution_name) VALUES (11030858, "Colomaplus eerste graad 1");
INSERT into Institution (synergy_id, institution_name) VALUES (99006589, "Commune d' Ecaussinnes");
INSERT into Institution (synergy_id, institution_name) VALUES (11017251, "De Boomhut");
INSERT into Institution (synergy_id, institution_name) VALUES(11017781, "De Fonkel");
INSERT into Institution (synergy_id, institution_name) VALUES (11017624, "De Leeuw");
INSERT into Institution (synergy_id, institution_name) VALUES (11131904, "De Negensprong");
INSERT into Institution (synergy_id, institution_name) VALUES (11017244, "De Revinze");
INSERT into Institution (synergy_id, institution_name) VALUES (11017798, "De Schatkist");
INSERT into Institution (synergy_id, institution_name) VALUES (11017632, "De Stapsteen");
INSERT into Institution (synergy_id, institution_name) VALUES (11026336, "De Torretjes");
INSERT into Institution (synergy_id, institution_name) VALUES (11017301, "De Tweesprong");
INSERT into Institution (synergy_id, institution_name) VALUES (11049445, "de! Kunsthumaniora van het GO!");
INSERT into Institution (synergy_id, institution_name) VALUES (11039057, "Don Bosco Genk");
INSERT into Institution (synergy_id, institution_name) VALUES (11038083, "Don Bosco Technisch Instituut");
INSERT into Institution (synergy_id, institution_name) VALUES (11126111, "Don Bosco Technisch Instituut 1");
INSERT into Institution (synergy_id, institution_name) VALUES (11039289, "Don Bosco-College");
INSERT into Institution (synergy_id, institution_name) VALUES (11032532, "Don Bosco-instituut ASO");
INSERT into Institution (synergy_id, institution_name) VALUES (11030056, "Don Bosco-Mariaberginstituut");
INSERT into Institution (synergy_id, institution_name) VALUES (11115683, "Driekoningen");
INSERT into Institution (synergy_id, institution_name) VALUES (11035931, "DvM - Humaniora");
INSERT into Institution (synergy_id, institution_name) VALUES (11035899, "DVM Handels-, Technisch en Beroepsonderwijs");
INSERT into Institution (synergy_id, institution_name) VALUES (12990187, "EESSCFV Verviers");
INSERT into Institution (synergy_id, institution_name) VALUES (11043216, "Einstein Atheneum, ASO Talen, Wetenschappen - Kuns");
INSERT into Institution (synergy_id, institution_name) VALUES (11127969, "Emmaës Aalter");
INSERT into Institution (synergy_id, institution_name) VALUES (11103424, "Eureka-Onderwijs");
INSERT into Institution (synergy_id, institution_name) VALUES (99006469, "Fam. Raes & De Bruyne");
INSERT into Institution (synergy_id, institution_name) VALUES (99000412, "Financiële dienst OCMW Koksijde");
INSERT into Institution (synergy_id, institution_name) VALUES (99006465, "Freinetschool Ibis");
INSERT into Institution (synergy_id, institution_name) VALUES (11033142, "Gemeentebestuur Londerzeel Dienst GTIL");
INSERT into Institution (synergy_id, institution_name) VALUES (11961458,"Gemeentebestuur van Boutersem");
INSERT into Institution (synergy_id, institution_name) VALUES (11961458, "Gemeentebestuur van Boutersem");
INSERT into Institution (synergy_id, institution_name) VALUES (11960724, "Gemeentebestuur van Herenthout");
INSERT into Institution (synergy_id, institution_name) VALUES (11960716, "Gemeentebestuur van Nijlen");
INSERT into Institution (synergy_id, institution_name) VALUES (11960575, "Gemeentebestuur van Stabroek");
INSERT into Institution (synergy_id, institution_name) VALUES (11975862, "Gemeentebestuur van Zele");
INSERT into Institution (synergy_id, institution_name) VALUES (11033548, "Gemeentelijk Instituut voor Technisch Onderwijs");
INSERT into Institution (synergy_id, institution_name) VALUES (11021841, "Gemeentelijke Basisschool");
INSERT into Institution (synergy_id, institution_name) VALUES (11022319, "Gemeentelijke Basisschool");
INSERT into Institution (synergy_id, institution_name) VALUES (11005462, "Gemeentelijke Basisschool - 't Groentje");
INSERT into Institution (synergy_id, institution_name) VALUES (11031161, "Gesubsidieerd Technisch Instituut");
INSERT into Institution (synergy_id, institution_name) VALUES (11030437, "Gitok bovenbouw");
INSERT into Institution (synergy_id, institution_name) VALUES (11007096, "GLS De Platanen");
INSERT into Institution (synergy_id, institution_name) VALUES (11040411, "GO! atheneum Boom");
INSERT into Institution (synergy_id, institution_name) VALUES (11002774, "GO! atheneum Campus Kompas");
INSERT into Institution (synergy_id, institution_name) VALUES (11116831, "GO! atheneum De Ring Leuven");
INSERT into Institution (synergy_id, institution_name) VALUES (11043141, "GO! atheneum Dendermonde");
INSERT into Institution (synergy_id, institution_name) VALUES (11042002, "GO! atheneum D'Hek Landen");
INSERT into Institution (synergy_id, institution_name) VALUES (11040642, "GO! atheneum Geel");
INSERT into Institution (synergy_id, institution_name) VALUES (11115394, "GO! atheneum Gentbrugge");
INSERT into Institution (synergy_id, institution_name) VALUES (11041533, "GO! atheneum Halle");
INSERT into Institution (synergy_id, institution_name) VALUES (11117754, "GO! Atheneum Heist");
INSERT into Institution (synergy_id, institution_name) VALUES (11040949, "GO! Atheneum Het Spoor");
INSERT into Institution (synergy_id, institution_name) VALUES (11000794, "GO! atheneum Lier basisschool Het Molentje");
INSERT into Institution (synergy_id, institution_name) VALUES (11000802, "GO! atheneum Lier basisschool Stadspark");
INSERT into Institution (synergy_id, institution_name) VALUES (11040816, "GO! atheneum Lier campus Anton Bergmann");
INSERT into Institution (synergy_id, institution_name) VALUES (11040808, "GO! atheneum Lier campus Arthur Vanderpoorten");
INSERT into Institution (synergy_id, institution_name) VALUES (11040832, "GO! atheneum Lier campus Louis Zimmer");
INSERT into Institution (synergy_id, institution_name) VALUES (11041038, "GO! atheneum Malle");
INSERT into Institution (synergy_id, institution_name) VALUES (11040972, "GO! atheneum Mortsel");
INSERT into Institution (synergy_id, institution_name) VALUES (11107706, "GO! atheneum Tervuren");
INSERT into Institution (synergy_id, institution_name) VALUES (11043273, "GO! atheneum Voskenslaan Gent");
INSERT into Institution (synergy_id, institution_name) VALUES (11041194, "GO! Atheneum Willebroek");
INSERT into Institution (synergy_id, institution_name) VALUES (11042408, "GO! atheneum Zwinstede Knokke");
INSERT into Institution (synergy_id, institution_name) VALUES (11000596, "GO! basisschool - De Zevensprong Nijlen");
INSERT into Institution (synergy_id, institution_name) VALUES (11000811, "GO! basisschool Bisterveld");
INSERT into Institution (synergy_id, institution_name) VALUES (11000828, "GO! basisschool De Bolster Mortsel");
INSERT into Institution (synergy_id, institution_name) VALUES (11001925, "GO! basisschool De Boomgaard Meerhout");
INSERT into Institution (synergy_id, institution_name) VALUES (11000562, "GO! basisschool De Boomgaard Wommelgem");
INSERT into Institution (synergy_id, institution_name) VALUES (11001206, "GO! basisschool De Cocon");
INSERT into Institution (synergy_id, institution_name) VALUES (11000356, "GO! basisschool De Duizendpootrakkers");
INSERT into Institution (synergy_id, institution_name) VALUES (11012047, "GO! basisschool De Esdoornschool");
INSERT into Institution (synergy_id, institution_name) VALUES (11137761, "GO! Basisschool De Glinster");
INSERT into Institution (synergy_id, institution_name) VALUES (11001222, "GO! basisschool De Letterboom Herselt");
INSERT into Institution (synergy_id, institution_name) VALUES (11000737, "GO! basisschool De Luchtballon");
INSERT into Institution (synergy_id, institution_name) VALUES (11123091, "GO! basisschool De LuchtballonTienen");
INSERT into Institution (synergy_id, institution_name) VALUES (11130922, "GO! basisschool De Notelaar");
INSERT into Institution (synergy_id, institution_name) VALUES (11044602, "GO! basisschool De Schakel Hoboken");
INSERT into Institution (synergy_id, institution_name) VALUES (11000851, "GO! basisschool De Schans");
INSERT into Institution (synergy_id, institution_name) VALUES (11000638, "GO! basisschool De Smiskens");
INSERT into Institution (synergy_id, institution_name) VALUES (11002543, "GO! basisschool De SpringplankTielt");
INSERT into Institution (synergy_id, institution_name) VALUES (11013433, "GO! basisschool De Suikerspin");
INSERT into Institution (synergy_id, institution_name) VALUES (11000703, "GO! basisschool De Vesten");
INSERT into Institution (synergy_id, institution_name) VALUES (11000273, "GO! basisschool De Vlinder");
INSERT into Institution (synergy_id, institution_name) VALUES (11000612, "GO! basisschool De Wijngaard Grobbendonk");
INSERT into Institution (synergy_id, institution_name) VALUES (11118679, "GO! basisschool De Wilg");
INSERT into Institution (synergy_id, institution_name) VALUES (11001917, "GO! basisschool De Wissel");
INSERT into Institution (synergy_id, institution_name) VALUES (11000752, "GO! basisschool De Zevensprong");
INSERT into Institution (synergy_id, institution_name) VALUES (11115972, "GO! basisschool Het Egeltje");
INSERT into Institution (synergy_id, institution_name) VALUES (11000687, "GO! basisschool Het Schrijvertje");
INSERT into Institution (synergy_id, institution_name) VALUES (11000281, "GO! basisschool Horizon Ternat");
INSERT into Institution (synergy_id, institution_name) VALUES (11000448, "GO! basisschool Irishof");
INSERT into Institution (synergy_id, institution_name) VALUES (11000621, "GO! basisschool Kameleon");
INSERT into Institution (synergy_id, institution_name) VALUES (11000869, "GO! basisschool Kiliaan");
INSERT into Institution (synergy_id, institution_name) VALUES (11001313, "GO! basisschool Klein AtheneumTienen");
INSERT into Institution (synergy_id, institution_name) VALUES (11001065, "GO! basisschool Lyceum");
INSERT into Institution (synergy_id, institution_name) VALUES (11011726, "GO! basisschool Maurits Sabbe");
INSERT into Institution (synergy_id, institution_name) VALUES (11000844, "GO! basisschool 't Groen Schooltje Hove");
INSERT into Institution (synergy_id, institution_name) VALUES (11000604, "GO! basisschool 't Klavertje");
INSERT into Institution (synergy_id, institution_name) VALUES (11000836, "GO! basisschool 't Kofschip");
INSERT into Institution (synergy_id, institution_name) VALUES (11000653, "GO! basisschool 't Locomotiefje");
INSERT into Institution (synergy_id, institution_name) VALUES (11001198, "GO! basisschool 't Wensbos");
INSERT into Institution (synergy_id, institution_name) VALUES (11137612, "GO! Basisschool Ten Dorpe");
INSERT into Institution (synergy_id, institution_name) VALUES (11011742, "GO! basisschool Victor Van De Walle");
INSERT into Institution (synergy_id, institution_name) VALUES (11000265, "GO! basisschool Vijverbeek");
INSERT into Institution (synergy_id, institution_name) VALUES (11025874, "GO! basisschool voor buitengewoon onderwijs - Den");
INSERT into Institution (synergy_id, institution_name) VALUES (11001503, "GO! basisschool VOX Pelt");
INSERT into Institution (synergy_id, institution_name) VALUES (11000729, "GO! basisschool Willem Tell");
INSERT into Institution (synergy_id, institution_name) VALUES (11040873, "GO! Busleyden Atheneum-campus Caputsteen");
INSERT into Institution (synergy_id, institution_name) VALUES (11131268, "GO! BuSO De Passer");
INSERT into Institution (synergy_id, institution_name) VALUES (11117838, "GO! Campus De Brug");
INSERT into Institution (synergy_id, institution_name) VALUES (11114272, "GO! centrum voor leerlingenbegeleiding Antwerpen");
INSERT into Institution (synergy_id, institution_name) VALUES (11048488, "GO! Centrum voor volwassenenonderwijs Cervo De Pan");
INSERT into Institution (synergy_id, institution_name) VALUES (11041178, "GO! Daltonatheneum Het Leerlabo");
INSERT into Institution (synergy_id, institution_name) VALUES (11001231, "GO! Daltonschool Het Leerlabo");
INSERT into Institution (synergy_id, institution_name) VALUES (11027284, "GO! De Varens");
INSERT into Institution (synergy_id, institution_name) VALUES (11035139, "GO! Ensorinstituut Oostende");
INSERT into Institution (synergy_id, institution_name) VALUES (11128827, "GO! freinetschool De Pientere Piste");
INSERT into Institution (synergy_id, institution_name) VALUES (99006466, "GO! Freinetschool De Regenboog");
INSERT into Institution (synergy_id, institution_name) VALUES (11000711, "GO! freinetschool De Vlindertuin Lille");
INSERT into Institution (synergy_id, institution_name) VALUES (11040923, "GO! Koninklijk Atheneum MXM");
INSERT into Institution (synergy_id, institution_name) VALUES (11040311, "GO! Koninklijk Lyceum Antwerpen");
INSERT into Institution (synergy_id, institution_name) VALUES (11110726, "GO! lagere school voor buitengewoon onderwijs - De");
INSERT into Institution (synergy_id, institution_name) VALUES (11043299, "GO! lyceum Gent");
INSERT into Institution (synergy_id, institution_name) VALUES (11042218, "GO! middenschool Brugge-centrum");
INSERT into Institution (synergy_id, institution_name) VALUES (11043588, "GO! middenschool De Moerbei Moerbeke-Waas");
INSERT into Institution (synergy_id, institution_name) VALUES (11042581, "GO! middenschool De vierboete Nieuwpoort");
INSERT into Institution (synergy_id, institution_name) VALUES (11040428, "GO! middenschool Den Brandt Boom");
INSERT into Institution (synergy_id, institution_name) VALUES (11043406, "GO! middenschool MIRA Hamme");
INSERT into Institution (synergy_id, institution_name) VALUES (11044669, "GO! middenschool Voskenslaan Gent");
INSERT into Institution (synergy_id, institution_name) VALUES (11042739, "GO! MSKA Roeselare Campus Groenestraat");
INSERT into Institution (synergy_id, institution_name) VALUES (11044081, "GO! Next het atheneum");
INSERT into Institution (synergy_id, institution_name) VALUES (99006144, "GO! Next methodeschool van Veldeke / Herx");
INSERT into Institution (synergy_id, institution_name) VALUES (11003467, "GO! Next MPI de Dageraad");
INSERT into Institution (synergy_id, institution_name) VALUES (11027219, "GO! SBSO de 3master");
INSERT into Institution (synergy_id, institution_name) VALUES (11027227, "GO! SBSO Groenlaar");
INSERT into Institution (synergy_id, institution_name) VALUES (11128967, "GO! SBSO Nautica");
INSERT into Institution (synergy_id, institution_name) VALUES (11113878, "GO! scholengroep Brussel");
INSERT into Institution (synergy_id, institution_name) VALUES (11113985, "GO! scholengroep Dender");
INSERT into Institution (synergy_id, institution_name) VALUES (11114017, "GO! scholengroep Gent");
INSERT into Institution (synergy_id, institution_name) VALUES (11113944, "GO! scholengroep Limburg Noord");
INSERT into Institution (synergy_id, institution_name) VALUES (11113852, "GO! scholengroep Rivierenland");
INSERT into Institution (synergy_id, institution_name) VALUES (11114009, "GO! scholengroep Vlaamse Ardennen");
INSERT into Institution (synergy_id, institution_name) VALUES (11113969, "GO! scholengroep Waasland");
INSERT into Institution (synergy_id, institution_name) VALUES (11113928, "GO! scholengroep Zuid-Limburg");
INSERT into Institution (synergy_id, institution_name) VALUES (11040717, "GO! SO De Vesten Herentals");
INSERT into Institution (synergy_id, institution_name) VALUES (11041152, "GO! Talentenschool Turnhout Campus Boomgaard MS");
INSERT into Institution (synergy_id, institution_name) VALUES (11990047, "GO! technisch atheneum campus Stabroek");
INSERT into Institution (synergy_id, institution_name) VALUES (11040584, "GO! technisch atheneum Da Vinci Edegem");
INSERT into Institution (synergy_id, institution_name) VALUES (11041004, "GO! technisch atheneum Den Biezerd");
INSERT into Institution (synergy_id, institution_name) VALUES (11041558, "GO! technisch atheneum Halle");
INSERT into Institution (synergy_id, institution_name) VALUES (11040782, "GO! technisch atheneum Kapellen");
INSERT into Institution (synergy_id, institution_name) VALUES (11032847, "GO! Technisch Atheneum Keerbergen");
INSERT into Institution (synergy_id, institution_name) VALUES (11043562, "GO! Tuinbouwschool Melle");
INSERT into Institution (synergy_id, institution_name) VALUES (11126045, "Guldensporencollege - Campus Gullegem");
INSERT into Institution (synergy_id, institution_name) VALUES (11123711, "Guldensporencollege - Campus Harelbeke");
INSERT into Institution (synergy_id, institution_name) VALUES (11123703, "Guldensporencollege - Campus Kaai");
INSERT into Institution (synergy_id, institution_name) VALUES (11125351, "Guldensporencollege - Campus Plein");
INSERT into Institution (synergy_id, institution_name) VALUES (11125377, "Guldensporencollege - Campus Zuid");
INSERT into Institution (synergy_id, institution_name) VALUES (11126052, "Guldensporencollege: Campus Engineering");
INSERT into Institution (synergy_id, institution_name) VALUES (11008219, "GVBS Annuncia Instituut");
INSERT into Institution (synergy_id, institution_name) VALUES (11960021, "Hartencollege VZW");
INSERT into Institution (synergy_id, institution_name) VALUES (11990044, "HBO5 Verpleegkunde Duffel Sint-Norbertusinstituut");
INSERT into Institution (synergy_id, institution_name) VALUES (99006455, "HBO5 -VIVES graduaat verpleegkunde");
INSERT into Institution (synergy_id, institution_name) VALUES (11030171, "Heilig Hart - Bovenbouw 1");
INSERT into Institution (synergy_id, institution_name) VALUES (11126102, "Heilig Hart van Maria Berlaar");
INSERT into Institution (synergy_id, institution_name) VALUES (11031351, "Heilig Hart van Maria-Instituut");
INSERT into Institution (synergy_id, institution_name) VALUES (11034471, "Heilige Familie Ieper");
INSERT into Institution (synergy_id, institution_name) VALUES (11127795, "Heilige Kindsheid");
INSERT into Institution (synergy_id, institution_name) VALUES (11032631, "Heilig-Hart-College 1");
INSERT into Institution (synergy_id, institution_name) VALUES (99005954, "Het Atelier Tienen");
INSERT into Institution (synergy_id, institution_name) VALUES (11033704, "Het College");
INSERT into Institution (synergy_id, institution_name) VALUES (11017616, "Het Dorp");
INSERT into Institution (synergy_id, institution_name) VALUES (99005952, "High Tech Campus Turnhout");
INSERT into Institution (synergy_id, institution_name) VALUES (11031468, "Hoger Instituut voor Verpleegkunde Sint-Elisabeth");
INSERT into Institution (synergy_id, institution_name) VALUES (11034124, "Hotel- en Toerismeschool Spermalie");
INSERT into Institution (synergy_id, institution_name) VALUES (1260410, "HTI Sint-Antonius");
INSERT into Institution (synergy_id, institution_name) VALUES (99006386, "Huis van het Kind");
INSERT into Institution (synergy_id, institution_name) VALUES(11037028, "Humaniora Nieuwen Bosch");
INSERT into Institution (synergy_id, institution_name) VALUES (12990191, "IEPSCF Mouscron");
INSERT into Institution (synergy_id, institution_name) VALUES (12990188, "IESPSCF Hannut");
INSERT into Institution (synergy_id, institution_name) VALUES (99006098, "Imelda-Instituut");
INSERT into Institution (synergy_id, institution_name) VALUES (11034496, "Immaculata Ieper");
INSERT into Institution (synergy_id, institution_name) VALUES (11031245, "Immaculata Instituut");
INSERT into Institution (synergy_id, institution_name) VALUES (11033944, "Immaculata Maria Instituut");
INSERT into Institution (synergy_id, institution_name) VALUES (11035253, "Immaculata-instituut");
INSERT into Institution (synergy_id, institution_name) VALUES (99006464, "Inge Coolkens");
INSERT into Institution (synergy_id, institution_name) VALUES (12000111, "Institut Sainte Marie Châtelineau");
INSERT into Institution (synergy_id, institution_name) VALUES (95111819023, "Institut Saint-Henri");
INSERT into Institution (synergy_id, institution_name) VALUES (11038935, "Instituut Maria Koningin");
INSERT into Institution (synergy_id, institution_name) VALUES (11110007, "Instituut Mariawende-Blydhove");
INSERT into Institution (synergy_id, institution_name) VALUES (11029447, "Instituut Maris Stella - Sint-Agnes");
INSERT into Institution (synergy_id, institution_name) VALUES (11047209, "Instituut Sint-Lutgardis");
INSERT into Institution (synergy_id, institution_name) VALUES (11028589, "Instituut Sint-Maria");
INSERT into Institution (synergy_id, institution_name) VALUES (11038653, "Instituut Stella Matutina");
INSERT into Institution (synergy_id, institution_name) VALUES (11048033, "Instituut Zusters Maricolen - Middenschool");
INSERT into Institution (synergy_id, institution_name) VALUES (11113829, "Invento GO! scholengroep");
INSERT into Institution (synergy_id, institution_name) VALUES (11968181, "IVG-Scholengroep VZW");
INSERT into Institution (synergy_id, institution_name) VALUES (11971101, "Katholiek Secundair onderwijs Maaseik-Kinrooi");
INSERT into Institution (synergy_id, institution_name) VALUES (11970442, "Katholieke Scholen Druivenstreek");
INSERT into Institution (synergy_id, institution_name) VALUES (11116145, "Katholieke Scholengroep RHIZO vzw");
INSERT into Institution (synergy_id, institution_name) VALUES (11123935, "Klein Seminarie");
INSERT into Institution (synergy_id, institution_name) VALUES (11990026, "KOBOS vzw");
INSERT into Institution (synergy_id, institution_name) VALUES (11037317, "KOHa Heilig Hart");
INSERT into Institution (synergy_id, institution_name) VALUES (11037309, "KOHa Sint-Jozef");
INSERT into Institution (synergy_id, institution_name) VALUES (11033712, "KOV vzw Virgoplus");
INSERT into Institution (synergy_id, institution_name) VALUES (11050658, "Kunsthumaniora Sint-Lucas");
INSERT into Institution (synergy_id, institution_name) VALUES (11035097, "Land- en Tuinbouwinstituut");
INSERT into Institution (synergy_id, institution_name) VALUES (11112136, "Leiepoort Deinze campus Sint-Hendrik, eerste graad");
INSERT into Institution (synergy_id, institution_name) VALUES (11036228, "Leiepoort Deinze campus Sint-Theresia");
INSERT into Institution (synergy_id, institution_name) VALUES (11107607, "Leiepoort Deinze campus Sint-Vincentius");
INSERT into Institution (synergy_id, institution_name) VALUES (11034512, "Lyceum Ieper");
INSERT into Institution (synergy_id, institution_name) VALUES (11115411, "Middenschool");
INSERT into Institution (synergy_id, institution_name) VALUES (11038851, "Middenschool Heilig Hartinstituut");
INSERT into Institution (synergy_id, institution_name) VALUES (11035238, "Middenschool Sint-Pieter");
INSERT into Institution (synergy_id, institution_name) VALUES (64037501, "Montessori College voor Vwo, Havo, Vmbo");
INSERT into Institution (synergy_id, institution_name) VALUES (12990183, "Notre-Dame des Champs Uccle");
INSERT into Institution (synergy_id, institution_name) VALUES (64128103, "NSG Groenewoud voor Vwo Havo en Mavo");
INSERT into Institution (synergy_id, institution_name) VALUES (99006343, "OCMW Ham");
INSERT into Institution (synergy_id, institution_name) VALUES (11105569, "Odisee");
INSERT into Institution (synergy_id, institution_name) VALUES (11017277, "Oefenschool");
INSERT into Institution (synergy_id, institution_name) VALUES (11028126, "Onze Jeugd");
INSERT into Institution (synergy_id, institution_name) VALUES (11034231, "Onze-Lieve-Vrouwecollege");
INSERT into Institution (synergy_id, institution_name) VALUES (11105395, "Onze-Lieve-Vrouwe-Instituut");
INSERT into Institution (synergy_id, institution_name) VALUES (11117036, "Onze-Lieve-Vrouwinstituut Middenschool 1");
INSERT into Institution (synergy_id, institution_name) VALUES (11053173, "Onze-Lieve-Vrouwinstituut Pulhof (ASO)");
INSERT into Institution (synergy_id, institution_name) VALUES (11029785, "Onze-Lieve-Vrouw-Presentatie - Middenschool");
INSERT into Institution (synergy_id, institution_name) VALUES (11036418, "Onze-Lieve-Vrouw-ten-Doorn");
INSERT into Institution (synergy_id, institution_name) VALUES (11127944, "Onze-Lieve-Vrouw-van-Lourdescollege");
INSERT into Institution (synergy_id, institution_name) VALUES (99006117, "Openbaar Centrum voor Maatschappelijk Welzijn");
INSERT into Institution (synergy_id, institution_name) VALUES (11137349, "OV4 De Branding");
INSERT into Institution (synergy_id, institution_name) VALUES (11007864, "OZCS-KOEPEL");
INSERT into Institution (synergy_id, institution_name) VALUES (11012633, "OZCS-KOEPEL");
INSERT into Institution (synergy_id, institution_name) VALUES (11031344, "OZCS-KOEPEL");
INSERT into Institution (synergy_id, institution_name) VALUES (11031591, "OZCS-KOEPEL");
INSERT into Institution (synergy_id, institution_name) VALUES (11031666, "OZCS-KOEPEL");
INSERT into Institution (synergy_id, institution_name) VALUES (11990040, "OZCS-KOEPEL");
INSERT into Institution (synergy_id, institution_name) VALUES (11035212, "Petrus - Paulus Centrum Sint-Jozefinstituut");
INSERT into Institution (synergy_id, institution_name) VALUES (11035162, "Petrus & Paulus VZW & College");
INSERT into Institution (synergy_id, institution_name) VALUES (11110395, "Priester Daens College - VTI Aalst 2");
INSERT into Institution (synergy_id, institution_name) VALUES (11034579, "Prizma - Campus College");
INSERT into Institution (synergy_id, institution_name) VALUES (11034561, "Prizma - Campus IdP");
INSERT into Institution (synergy_id, institution_name) VALUES (11034553, "Prizma - Campus VTI");
INSERT into Institution (synergy_id, institution_name) VALUES (11034538, "Prizma - Middenschool Ingelmunster");
INSERT into Institution (synergy_id, institution_name) VALUES (11034587, "Prizma - Middenschool Izegem 1");
INSERT into Institution (synergy_id, institution_name) VALUES (11034942, "Prizma - Middenschool Lendelede");
INSERT into Institution (synergy_id, institution_name) VALUES (12000013, "Province de Hainaut");
INSERT into Institution (synergy_id, institution_name) VALUES (11050096, "Provinciale Secundaire School Hasselt");
INSERT into Institution (synergy_id, institution_name) VALUES (99006454, "Rhizo - VIVATO Kortrijk");
INSERT into Institution (synergy_id, institution_name) VALUES (11112789, "RHIZO 7 BuSO De Lage Kouter");
INSERT into Institution (synergy_id, institution_name) VALUES (11138743, "RHIZO BuSO De Hoge Kouter");
INSERT into Institution (synergy_id, institution_name) VALUES (11127811, "Sancta Maria Leuven");
INSERT into Institution (synergy_id, institution_name) VALUES (1232462, "SBSO Baken");
INSERT into Institution (synergy_id, institution_name) VALUES (11030742, "Scheppersinstituut");
INSERT into Institution (synergy_id, institution_name) VALUES (11118281, "Scheppersinstituut 1");
INSERT into Institution (synergy_id, institution_name) VALUES (11047258, "Scheppersinstituut 1 Deurne - Antwerpen");
INSERT into Institution (synergy_id, institution_name) VALUES (11043729, "Scholen Da Vinci");
INSERT into Institution (synergy_id, institution_name) VALUES (11971796, "Scholen Molenland vzw");
INSERT into Institution (synergy_id, institution_name) VALUES (11113886, "Scholengroep 9 - Ringscholen");
INSERT into Institution (synergy_id, institution_name) VALUES (11972679, "Secundair Onderwijs Dominiek Savio");
INSERT into Institution (synergy_id, institution_name) VALUES (12000199, "SEMINAIRE DE BONNE ESPERANCE");
INSERT into Institution (synergy_id, institution_name) VALUES (12990006, "Simila Asbl");
INSERT into Institution (synergy_id, institution_name) VALUES (64009403, "Sint Gregorius College Scholengemeenschap voor Ath");
INSERT into Institution (synergy_id, institution_name) VALUES (11034181, "Sint-Andreasinstituut");
INSERT into Institution (synergy_id, institution_name) VALUES (11035154, "Sint-Andreasinstituut");
INSERT into Institution (synergy_id, institution_name) VALUES (11034272, "Sint-Andreaslyceum");
INSERT into Institution (synergy_id, institution_name) VALUES (11047282, "Sint-Annacollege");
INSERT into Institution (synergy_id, institution_name) VALUES (11126797, "Sint-Augustinusinstituut ASO");
INSERT into Institution (synergy_id, institution_name) VALUES (11036962, "Sint-Barbaracollege");
INSERT into Institution (synergy_id, institution_name) VALUES (11036996, "Sint-Bavohumaniora");
INSERT into Institution (synergy_id, institution_name) VALUES (11105411, "Sint-Bernarduscollege");
INSERT into Institution (synergy_id, institution_name) VALUES (11031187, "Sint-Calasanzinstituut");
INSERT into Institution (synergy_id, institution_name) VALUES (11036608, "Sint-Catharinacollege1");
INSERT into Institution (synergy_id, institution_name) VALUES (11029454, "Sint-Claracollege");
INSERT into Institution (synergy_id, institution_name) VALUES (11033209, "Sint-Donatusinstituut");
INSERT into Institution (synergy_id, institution_name) VALUES (11033241, "Sint-Donatusinstituut - Middenschool");
INSERT into Institution (synergy_id, institution_name) VALUES (11030941, "Sint-Eduardusinstituut");
INSERT into Institution (synergy_id, institution_name) VALUES (11037598, "Sint-Franciscusinstituut");
INSERT into Institution (synergy_id, institution_name) VALUES (11038158, "Sint-Franciscusinstituut");
INSERT into Institution (synergy_id, institution_name) VALUES (11034165, "Sint-Franciscus-Xaveriusinstituut");
INSERT into Institution (synergy_id, institution_name) VALUES (11123761, "Sint-Gabrielcollege");
INSERT into Institution (synergy_id, institution_name) VALUES (11972513, "Sint-Gerardusscholen");
INSERT into Institution (synergy_id, institution_name) VALUES (11034389, "Sint-Godelievecollege");
INSERT into Institution (synergy_id, institution_name) VALUES (11032052, "Sint-Guido-Instituut");
INSERT into Institution (synergy_id, institution_name) VALUES (11033993, "Sint-Jan Berchmanscollege");
INSERT into Institution (synergy_id, institution_name) VALUES (11115352, "Sint-Janscollege");
INSERT into Institution (synergy_id, institution_name) VALUES (99027541, "Sint-Jozef OV4");
INSERT into Institution (synergy_id, institution_name) VALUES (11031336, "Sint-Jozefinstituut");
INSERT into Institution (synergy_id, institution_name) VALUES (11034058, "Sint-Jozefsinstituut")
INSERT into Institution (synergy_id, institution_name) VALUES (11036616, "Sint-Jozefsinstituut");
INSERT into Institution (synergy_id, institution_name) VALUES (11034611, "Sint-Jozefsinstituut Lyceum");
INSERT into Institution (synergy_id, institution_name) VALUES (11030155, "Sint-Lambertusinstituut");
INSERT into Institution (synergy_id, institution_name) VALUES (11105486, "Sint-Laurensinstituut - ASO");
INSERT into Institution (synergy_id, institution_name) VALUES (11109959, "Sint-Lievenscollege");
INSERT into Institution (synergy_id, institution_name) VALUES (11127696, "Sint-Lievenscollege");
INSERT into Institution (synergy_id, institution_name) VALUES (11036913, "Sint-Lievenscollege Business");
INSERT into Institution (synergy_id, institution_name) VALUES (11123802, "Sint-Lodewijkscollege");
INSERT into Institution (synergy_id, institution_name) VALUES (11029058, "Sint-Lucas Kunstsecundair");
INSERT into Institution (synergy_id, institution_name) VALUES (11127481, "Sint-Ludgardisschool");
INSERT into Institution (synergy_id, institution_name) VALUES (11031054, "Sint-Lutgardis");
INSERT into Institution (synergy_id, institution_name) VALUES (11034017, "Sint-Lutgartinstituut");
INSERT into Institution (synergy_id, institution_name) VALUES (11039313, "Sint-Martinusscholen 039313");
INSERT into Institution (synergy_id, institution_name) VALUES (11032078, "Sint-Martinusscholen TSO-BSO");
INSERT into Institution (synergy_id, institution_name) VALUES (11126003, "Sint-Norbertusinstituut 1");
INSERT into Institution (synergy_id, institution_name) VALUES (11037325, "Sint-Paulusinstituut");
INSERT into Institution (synergy_id, institution_name) VALUES (11127531, "Sint-Paulusinstituut 1");
INSERT into Institution (synergy_id, institution_name) VALUES (11123571, "Sint-Pietersinstituut");
INSERT into Institution (synergy_id, institution_name) VALUES (11030759, "Sint-Romboutscollege");
INSERT into Institution (synergy_id, institution_name) VALUES (11109843, "Sint-Ursula-Instituut");
INSERT into Institution (synergy_id, institution_name) VALUES (11031476, "Sint-Victorinstituut");
INSERT into Institution (synergy_id, institution_name) VALUES (11036152, "Sint-Vincentiuscollege");
INSERT into Institution (synergy_id, institution_name) VALUES (11047217, "Sint-Vincentiuscollege - Middenschool");
INSERT into Institution (synergy_id, institution_name) VALUES (11035592, "SIVI");
INSERT into Institution (synergy_id, institution_name) VALUES (11131391, "SLHD Secundaire school - Bovenbouw");
INSERT into Institution (synergy_id, institution_name) VALUES (11034661, "SMIK");
INSERT into Institution (synergy_id, institution_name) VALUES (11035824, "SPES");
INSERT into Institution (synergy_id, institution_name) VALUES (11048091, "Sport- en Handelsschool Turnhout");
INSERT into Institution (synergy_id, institution_name) VALUES (11990014, "Stamina");
INSERT into Institution (synergy_id, institution_name) VALUES (11061937, "Stella Matutinacollege");
INSERT into Institution (synergy_id, institution_name) VALUES (11031807, "Stella Matutina-Instituut");
INSERT into Institution (synergy_id, institution_name) VALUES (11062174, "Stfran. Campus Gasthuisberg");
INSERT into Institution (synergy_id, institution_name) VALUES (64151300, "Stg. Johan de Witt-gymnasium te Dordrecht");
INSERT into Institution (synergy_id, institution_name) VALUES (61374900, "Stichting Gemeentelijk Gymnasium Hilversum");
INSERT into Institution (synergy_id, institution_name) VALUES (61373900, "Stichting RSG Slingerbos - Levant");
INSERT into Institution (synergy_id, institution_name) VALUES (11017194, "t Vlot");
INSERT into Institution (synergy_id, institution_name) VALUES (11125971, "Talentenschool Turnhout campusBoomgaard KA");
INSERT into Institution (synergy_id, institution_name) VALUES (11034082, "Technisch Instituut Heilige Familie");
INSERT into Institution (synergy_id, institution_name) VALUES (11123786, "Technisch Instituut Sint-Paulus");
INSERT into Institution (synergy_id, institution_name) VALUES (11126185, "Technische Scholen Mechelen");
INSERT into Institution (synergy_id, institution_name) VALUES (11033721, "TechnOV");
INSERT into Institution (synergy_id, institution_name) VALUES (11017236, "Ten Parke");
INSERT into Institution (synergy_id, institution_name) VALUES (11128553, "TISM");
INSERT into Institution (synergy_id, institution_name) VALUES (11122739, "Ursulinen Mechelen 1");
INSERT into Institution (synergy_id, institution_name) VALUES (11131342, "V.T.I. Zeebrugge");
INSERT into Institution (synergy_id, institution_name) VALUES (11035378, "VABI");
INSERT into Institution (synergy_id, institution_name) VALUES (64072203, "Vechtdal College Dedemsvaart");
INSERT into Institution (synergy_id, institution_name) VALUES (64072202, "Vechtdal College Ommen");
INSERT into Institution (synergy_id, institution_name) VALUES (64072201, "Vechtdal College Scholengemeenschap voor Atheneum");
INSERT into Institution (synergy_id, institution_name) VALUES (99006628, "Ville de Charleroi Service des aines");
INSERT into Institution (synergy_id, institution_name) VALUES (99000277, "Ville de HERSTAL");
INSERT into Institution (synergy_id, institution_name) VALUES (11033134, "Virgo Sapiensinstituut");
INSERT into Institution (synergy_id, institution_name) VALUES (11037581, "Visitatie");
INSERT into Institution (synergy_id, institution_name) VALUES (11123976, "VISO");
INSERT into Institution (synergy_id, institution_name) VALUES (11007021, "VLS Zilverenhoek Maria Immaculata");
INSERT into Institution (synergy_id, institution_name) VALUES (11035601, "VLTI");
INSERT into Institution (synergy_id, institution_name) VALUES (11127753, "VMS");
INSERT into Institution (synergy_id, institution_name) VALUES (11034331, "Vrij Handels- en Sportinstituut Sint-Michiels");
INSERT into Institution (synergy_id, institution_name) VALUES (11048975, "Vrij Instituut voor Secundair Onderwijs Cor Mariae");
INSERT into Institution (synergy_id, institution_name) VALUES (11036939, "Vrij Instituut voor Secundair Onderwijs-Mariakerke");
INSERT into Institution (synergy_id, institution_name) VALUES (11030361, "Vrij Instituut voor Technisch Onderwijs");
INSERT into Institution (synergy_id, institution_name) VALUES (11034074, "Vrij Technisch Instituut Brugge");
INSERT into Institution (synergy_id, institution_name) VALUES (11036202, "Vrij Technisch Instituut Deinze");
INSERT into Institution (synergy_id, institution_name) VALUES (11004994, "Vrije Basisschool");
INSERT into Institution (synergy_id, institution_name) VALUES (11005983, "Vrije Basisschool");
INSERT into Institution (synergy_id, institution_name) VALUES (11008326, "Vrije Basisschool");
INSERT into Institution (synergy_id, institution_name) VALUES (11011007, "Vrije Basisschool");
INSERT into Institution (synergy_id, institution_name) VALUES (11019513, "Vrije Basisschool");
INSERT into Institution (synergy_id, institution_name) VALUES (11019653, "Vrije Basisschool");
INSERT into Institution (synergy_id, institution_name) VALUES (11023945, "Vrije Basisschool");
INSERT into Institution (synergy_id, institution_name) VALUES (11055939, "Vrije Basisschool");
INSERT into Institution (synergy_id, institution_name) VALUES (11022954, "Vrije Basisschool");
INSERT into Institution (synergy_id, institution_name) VALUES (11015727, "Vrije Basisschool - de Bammerd- Beukenbroekje");
INSERT into Institution (synergy_id, institution_name) VALUES (11016683, "Vrije Basisschool - De Heppening");
INSERT into Institution (synergy_id, institution_name) VALUES (11045351, "Vrije Basisschool - De Klimming");
INSERT into Institution (synergy_id, institution_name) VALUES (11127068, "Vrije Basisschool - De Lanetuin");
INSERT into Institution (synergy_id, institution_name) VALUES (11130881, "Vrije Basisschool - De Leerheide");
INSERT into Institution (synergy_id, institution_name) VALUES (11010553, "Vrije Basisschool - De Wingerd");
INSERT into Institution (synergy_id, institution_name) VALUES (11012666, "Vrije Basisschool - Heilig-Hartcollege");
INSERT into Institution (synergy_id, institution_name) VALUES (11047027, "Vrije Basisschool - Klaproos");
INSERT into Institution (synergy_id, institution_name) VALUES (1105827, "Vrije Basisschool - O.-L.-V. Jezus-Eik");
INSERT into Institution (synergy_id, institution_name) VALUES (11107839, "Vrije Basisschool - Onze Lieve Vrouw Presentatie");
INSERT into Institution (synergy_id, institution_name) VALUES (11022351, "Vrije Basisschool - Onze-Lieve-Vrouwcollege");
INSERT into Institution (synergy_id, institution_name) VALUES (11014811, "Vrije Basisschool - Oud-Waterschei - 't schoolke");
INSERT into Institution (synergy_id, institution_name) VALUES (11007112, "Vrije Basisschool - Sint-Calasanz");
INSERT into Institution (synergy_id, institution_name) VALUES (11007765, "Vrije Basisschool - Sint-Elisabethschool");
INSERT into Institution (synergy_id, institution_name) VALUES (11021791, "Vrije Basisschool - Sint-Janscollege - Oude Bareel");
INSERT into Institution (synergy_id, institution_name) VALUES (11045286, "Vrije Basisschool - Sint-Maartenschool");
INSERT into Institution (synergy_id, institution_name) VALUES (11010009, "Vrije Basisschool - Sleutelhof");
INSERT into Institution (synergy_id, institution_name) VALUES (11011973, "Vrije Basisschool - Virgo De Heide");
INSERT into Institution (synergy_id, institution_name) VALUES (11023011, "Vrije Basisschool - Visitatie");
INSERT into Institution (synergy_id, institution_name) VALUES (11009993, "Vrije Basisschool - Vosberg");
INSERT into Institution (synergy_id, institution_name) VALUES (11017061, "Vrije Basisschool De Regenboog");
INSERT into Institution (synergy_id, institution_name) VALUES (11008409, "Vrije Basisschool De Zandloper");
INSERT into Institution (synergy_id, institution_name) VALUES (11138487, "Vrije Basisschool Harduynschool");
INSERT into Institution (synergy_id, institution_name) VALUES (11022988, "Vrije Basisschool HeHaSchool");
INSERT into Institution (synergy_id, institution_name) VALUES (11008474, "Vrije Basisschool Klavertjedrie");
INSERT into Institution (synergy_id, institution_name) VALUES (11005835, "Vrije Basisschool Maleizen");
INSERT into Institution (synergy_id, institution_name) VALUES (11022525, "Vrije Basisschool Oosterzele");
INSERT into Institution (synergy_id, institution_name) VALUES (11022673, "Vrije Basisschool ORS De Duizendpoot");
INSERT into Institution (synergy_id, institution_name) VALUES (11022962, "Vrije Basisschool ORS vzw Campus Appels-Oudegem");
INSERT into Institution (synergy_id, institution_name) VALUES (11005819, "Vrije Basisschool Sint-Jozef");
INSERT into Institution (synergy_id, institution_name) VALUES (11108225, "Vrije Basisschool Sint-Katrien");
INSERT into Institution (synergy_id, institution_name) VALUES (11019588, "Vrije Basisschool Sint-Pieter");
INSERT into Institution (synergy_id, institution_name) VALUES (11019562, "Vrije Basisschool St-Michiel");
INSERT into Institution (synergy_id, institution_name) VALUES (11007741, "Vrije Basisschool 't Klavernest");
INSERT into Institution (synergy_id, institution_name) VALUES (11027078, "Vrije Basisschool voor Buitengewoon Onderwijs - De");
INSERT into Institution (synergy_id, institution_name) VALUES (11102681, "Vrije Kleuterschool - De Zevensprong");
INSERT into Institution (synergy_id, institution_name) VALUES (11007799, "Vrije Lagere School - Sint-Michiel");
INSERT into Institution (synergy_id, institution_name) VALUES (11011981, "Vrije Lagere School - Virgo Sapiens");
INSERT into Institution (synergy_id, institution_name) VALUES (11021303, "Vrije Lagere School Slotendries");
INSERT into Institution (synergy_id, institution_name) VALUES (11019505, "Vrije Lagere School SpesNostra");
INSERT into Institution (synergy_id, institution_name) VALUES (11008482, "Vrije Lagere School Windekind");
INSERT into Institution (synergy_id, institution_name) VALUES (11006023, "Vrije Sint-Clemensschool Lagere School");
INSERT into Institution (synergy_id, institution_name) VALUES (11116971, "Vrije Technische Scholen van Turnhout");
INSERT into Institution (synergy_id, institution_name) VALUES (11035634, "VTI");
INSERT into Institution (synergy_id, institution_name) VALUES (11035659, "VTI");
INSERT into Institution (synergy_id, institution_name) VALUES (11127779, "VTI");
INSERT into Institution (synergy_id, institution_name) VALUES (11034462, "VTI Ieper");
INSERT into Institution (synergy_id, institution_name) VALUES (11108621, "vzw christelijke scholen Briljant");
INSERT into Institution (synergy_id, institution_name) VALUES (11970111, "VZW Comite voor Onderwijs Annuntiaten Heverlee");
INSERT into Institution (synergy_id, institution_name) VALUES (11108845, "vzw EDUGO Scholengroep");
INSERT into Institution (synergy_id, institution_name) VALUES (11962829, "VZW Heilig Hartcollege Tervuren");
INSERT into Institution (synergy_id, institution_name) VALUES (11968751, "VZW INIGO,ignatiaanse scholen");
INSERT into Institution (synergy_id, institution_name) VALUES (11972851, "VZW Inspirocollege");
INSERT into Institution (synergy_id, institution_name) VALUES (11963967, "VZW Instituut Sint-Carolus");
INSERT into Institution (synergy_id, institution_name) VALUES (11963363, "VZW Instituut van het Heilig Graf");
INSERT into Institution (synergy_id, institution_name) VALUES (11971333, "VZW Instituut voor Voeding");
INSERT into Institution (synergy_id, institution_name) VALUES (11973776, "VZW Katholiek Basisonderwijs Neeroeteren");
INSERT into Institution (synergy_id, institution_name) VALUES (11110585, "vzw Katholiek Onderwijs Dijle Demer");
INSERT into Institution (synergy_id, institution_name) VALUES (11971341, "VZW Katholiek Onderwijs Hinterland");
INSERT into Institution (synergy_id, institution_name) VALUES (11107458, "VZW Katholiek Onderwijs Regio Lier");
INSERT into Institution (synergy_id, institution_name) VALUES (11972083, "VZW Katholiek Secundair Onderwijs Oudenaarde - KSO");
INSERT into Institution (synergy_id, institution_name) VALUES (11055277, "VZW Katholiek Secundair Onderwijs Zottegem");
INSERT into Institution (synergy_id, institution_name) VALUES (11118612, "VZW Katholieke Basisscholen Regio Poperinge");
INSERT into Institution (synergy_id, institution_name) VALUES (11056291, "VZW KOBArT");
INSERT into Institution (synergy_id, institution_name) VALUES (11972166, "VZW KOBeL");
INSERT into Institution (synergy_id, institution_name) VALUES (11990020, "VZW KOMO");
INSERT into Institution (synergy_id, institution_name) VALUES (11971309, "VZW KSO Diksmuide ('t Saam)");
INSERT into Institution (synergy_id, institution_name) VALUES (11039271, "VZW KSO Hasselt - Humaniora Kindsheid Jesu");
INSERT into Institution (synergy_id, institution_name) VALUES (11116161, "VZW KSO Veurne-De Panne-Nieuwpoort");
INSERT into Institution (synergy_id, institution_name) VALUES (11061507, "vzw KSOM - Campus de Helix");
INSERT into Institution (synergy_id, institution_name) VALUES (11133331, "Vzw LKSD Afdeling Stroom");
INSERT into Institution (synergy_id, institution_name) VALUES (11974584, "VZW Margareta-Maria Instituut");
INSERT into Institution (synergy_id, institution_name) VALUES (11974791, "VZW Mariagaard - Zusters van Liefde Kwatrecht");
INSERT into Institution (synergy_id, institution_name) VALUES (11974386, "VZW Onderwijscentrum Bokrijk");
INSERT into Institution (synergy_id, institution_name) VALUES (11111096, "VZW Onze-Lieve-Vrouwinstituut Boom");
INSERT into Institution (synergy_id, institution_name) VALUES (11968818, "VZW Opvoeding en Cultuur van de Zusters van Gijzeg");
INSERT into Institution (synergy_id, institution_name) VALUES (99006443, "vzw Organisatie Broeders van Liefde - Leotes");
INSERT into Institution (synergy_id, institution_name) VALUES (11968842, "VZW Oscar Romeroscholen");
INSERT into Institution (synergy_id, institution_name) VALUES (11974824, "VZW Priester Daens College");
INSERT into Institution (synergy_id, institution_name) VALUES (11963942, "VZW Scholen OLVP Sint-Niklaas");
INSERT into Institution (synergy_id, institution_name) VALUES (11116152, "VZW Scholengroep Sint-Michiel");
INSERT into Institution (synergy_id, institution_name) VALUES (11964858, "VZW Schoolbestuur Sint-Paulus");
INSERT into Institution (synergy_id, institution_name) VALUES (11964213, "VZW Sint-Amandus Basisschool Malderen");
INSERT into Institution (synergy_id, institution_name) VALUES (11053819, "VZW Sint-Franciscuscollege Heusden-Zolder");
INSERT into Institution (synergy_id, institution_name) VALUES (11117952, "VZW Sint-Goedele Brussel");
INSERT into Institution (synergy_id, institution_name) VALUES (11963835, "VZW Sint-Jan Berchmansinstituut");
INSERT into Institution (synergy_id, institution_name) VALUES (11113787, "VZW Sint-Maartensscholen Ieper");
INSERT into Institution (synergy_id, institution_name) VALUES (11035741, "VZW Sint-Paulusschool campus College");
INSERT into Institution (synergy_id, institution_name) VALUES (11968115, "VZW Sint-Pietersinstituut");
INSERT into Institution (synergy_id, institution_name) VALUES (11974485, "VZW Spes Nostra");
INSERT into Institution (synergy_id, institution_name) VALUES (11114165, "VZW V.S.O.P. Sint-Bertinus");
INSERT into Institution (synergy_id, institution_name) VALUES (11970971, "VZW Verenigde Instituten Secundair Onderwijs Sint-");
INSERT into Institution (synergy_id, institution_name) VALUES (11971937, "VZW Vrij Lokers Onderwijs voor jouw Toekomst (VLOT");
INSERT into Institution (synergy_id, institution_name) VALUES (11974295, "VZW Vrij Technisch Instituut Leuven");
INSERT into Institution (synergy_id, institution_name) VALUES (11017269, "Wijnendale");
INSERT into Institution (synergy_id, institution_name) VALUES (11029751, "Xaveriuscollege");
INSERT into Institution (synergy_id, institution_name) VALUES (11104729, "ZAVO vzw");
INSERT into Institution (synergy_id, institution_name) VALUES (11104729, "ZAVO vzw");
